import {
	HouseLine,
	AddressBook,
	IdentificationBadge,
	IdentificationCard, 
	Calendar,
	EnvelopeSimple,
	Phone,
	House,
	TextH,
	TextAlignLeft,
	GenderIntersex,
	File,
	PhoneSlash,
	RadioButton,
  ListChecks
} from "phosphor-react"

export const tools = [
  {
    id: 1,
    title: 'Full Name',
    name: 'fullname',
    inputType: 'text',
    required: true,
    label: 'Enter your Full Name',
    placeholder: 'John Doe',
    icon: <IdentificationCard size={18} />,
  },
  {
    id: 2,
    title: 'Email',
    name: 'email',
    inputType: 'email',
    required: true,
    placeholder: 'johndoe@email.com',
    label: 'Email',
    icon: <EnvelopeSimple size={18} />,
  },
  {
    id: 3,
    title: 'Phone',
    name: 'phone',
    inputType: 'number',
    required: true,
    placeholder: '0902289333',
    label: 'Phone',
    icon: <Phone size={18} />,
  },
  {
    id: 4,
    title: 'Address',
    name: 'address',
    inputType: 'text',
    required: true,
    placeholder: 'No. 8 Abuja street, maitama',
    label: 'Address',
    icon: <House size={18} />,
  },
  {
    id: 7,
    title: 'Gender',
    name: 'gender',
    inputType: 'select',
    required: true,
    label: 'Please select your gender',
    selectable: [
      {
        label: 'female',
        value: 'female',
        selected: true,
      },
      {
        label: 'male',
        value: 'male',
        selected: false,
      },
    ],
    icon: <GenderIntersex size={18} />,
  },

  {
    id: 8,
    title: 'File',
    name: 'file',
    inputType: 'file',
    required: true,
    placeholder: 'File',
    label: 'File',
    icon: <File size={18} />,
  },
  {
    id: 9,
    title: 'Date of birth',
    name: 'dob',
    inputType: 'date',
    placeholder: 'Date of birth',
    required: true,
    label: 'Date of birth',
    icon: <Calendar size={18} />,
  },
  {
    id: 10,
    title: 'Bvn',
    name: 'bvn',
    inputType: 'number',
    required: true,
    placeholder: 'Enter Bank Verification Number',
    label: 'Bank Verification Number ',
    icon: <IdentificationBadge size={18} />,
  },
  {
    id: 11,
    title: 'Date Picker',
    name: 'date picker',
    inputType: 'date',
    required: true,
    placeholder: '',
    label: 'Date',
    icon: <Calendar size={18} />,
  },
  {
    id: 12,
    title: 'NIN',
    name: 'nin',
    inputType: 'number',
    required: true,
    placeholder: 'Enter Nin',
    label: 'National Identity Number',
    icon: <IdentificationCard size={18} />,
  },
  {
    id: 13,
    title: 'Passport',
    name: 'passport',
    inputType: 'file',
    required: true,
    placeholder: '',
    label: 'Passport',
    icon: <IdentificationCard size={18} />,
  },
  {
    id: 14,
    title: 'Nationality',
    name: 'nationality',
    inputType: 'text',
    required: true,
    placeholder: '',
    label: 'Nationality',
    icon: <AddressBook size={18} />,
  },
  {
    id: 15,
    title: 'State of origin',
    name: 'state of origin',
    inputType: 'text',
    required: true,
    placeholder: 'Enter state of origin',
    label: 'state of origin',
    icon: <IdentificationCard size={18} />,
  },
  {
    id: 16,
    title: 'Marital status',
    name: 'marital status',
    inputType: 'select',
    required: true,
    label: 'Please confirm your marital status',
    selectable: [
      {
        label: 'married',
        value: 'married',
        selected: true,
      },
      {
        label: 'single',
        value: 'single',
        selected: false,
      },
    ],
    icon: <IdentificationCard size={18} />,
  },
  {
    id: 17,
    title: 'Document upload',
    name: 'document upload',
    inputType: 'file',
    required: true,
    placeholder: 'file',
    label: 'file',
    icon: <IdentificationCard size={18} />,
  },
  {
    id: 18,
    title: 'Next of kin',
    name: 'next of kin',
    inputType: 'text',
    required: true,
    placeholder: '',
    label: '',
    icon: <IdentificationCard size={18} />,
  },
  {
    id: 19,
    title: 'Current location',
    name: 'current location',
    inputType: 'text',
    required: true,
    placeholder: 'current location',
    label: 'current location',
    icon: <House size={18} />,
  },
  {
    id: 20,
    title: 'Text field',
    name: 'text field',
    inputType: 'text',
    required: true,
    placeholder: 'text',
    label: 'text field',
    icon: <TextH size={18} />,
  },
  {
    id: 21,
    title: 'Number field',
    name: 'number field',
    inputType: 'number',
    required: true,
    placeholder: 'enter number',
    label: 'number',
    icon: <PhoneSlash size={18} />,
  },
  {
    id: 22,
    title: 'Text input field',
    name: 'text input field',
    inputType: 'text',
    required: true,
    placeholder: 'Enter text',
    label: 'current location',
    icon: <text size={18} />,
  },
  {
    id: 23,
    title: 'Local Government',
    name: 'LGA',
    inputType: 'text',
    required: true,
    placeholder: 'LGA',
    label: 'LGA',
    icon: <HouseLine size={18} />,
  },
  {
    id: 16,
    title: 'Select',
    name: 'select',
    inputType: 'select',
    required: true,
    label: 'select',
    selectable: [
      {
        label: 'select 1',
        value: 'select 1',
        selected: true,
      },
      {
        label: 'select 2',
        value: 'select 2',
        selected: false,
      },
    ],
    icon: <ListChecks size={18} />,
  },
  {
    id: 24,
    title: 'Radio button',
    name: 'radio button',
    inputType: 'radio',
    required: true,
    placeholder: 'radio',
    label: 'radio',
    icon: <RadioButton size={18} />,
  },
  {
    id: 25,
    title: 'Multiple Select',
    name: 'multiple select',
    inputType: 'multiple select',
    required: true,
    placeholder: 'multiple select',
    label: 'multiple select',
    data: [],
    selectable: [
      {
        label: 'option 1',
        value: 'option 1',
        selected: true,
      },
      {
        label: 'option 2',
        value: 'option 2',
        selected: false,
      },
    ],
    icon: <ListChecks size={18} />,
  },
]