export const GET_ORGANISTION_LIST = 'GET_ORGANISTION_LIST'
export const GET_ORGANISTION_LIST_SUCCESS = 'GET_ORGANISTION_LIST_SUCCESS'
export const GET_ORGANISTION_LIST_FAILED = 'GET_ORGANISTION_LIST_FAILED'

export const ADD_ORGANISATION = 'ADD_ORGANISATION'
export const ADD_ORGANISATION_SUCCESS = 'ADD_ORGANISATION_SUCCESS'
export const ADD_ORGANISATION_FAILED = 'ADD_ORGANISATION_FAILED'

export const GET_SINGLE_ORGANISATION = 'GET_SINGLE_ORGANISATION'
export const GET_SINGLE_ORGANISATION_SUCCESS = 'GET_SINGLE_ORGANISATION_SUCCESS'
export const GET_SINGLE_ORGANISATION_FAILED = 'GET_SINGLE_ORGANISATION_FAILED'

export const EDIT_ORGANISATION = 'EDIT_ORGANISATION'
export const EDIT_ORGANISATION_SUCCESS = 'EDIT_ORGANISATION_SUCCESS'
export const EDIT_ORGANISATION_FAILED = 'EDIT_ORGANISATION_FAILED'

export const DELETE_ORGANISATION = 'DELETE_ORGANISATION'
export const DELETE_ORGANISATION_SUCCESS = 'DELETE_ORGANISATION_SUCCESS'
export const DELETE_ORGANISATION_FAILED = 'DELETE_ORGANISATION_FAILED'

export const SELECTED_ORGANISATION = 'SELECTED_ORGANISATION'

export const CLEAR_ORGANISATION = 'CLEAR_ORGANISATION'
