export default Object.freeze({
  SAVE_APPLICANT_DETAILS_START: 'SAVE_APPLICANT_DETAILS_START',
  SAVE_APPLICANT_DETAILS_SUCCESS: 'SAVE_APPLICANT_DETAILS_SUCCESS',
  SAVE_APPLICANT_DETAILS_FAILED: 'SAVE_APPLICANT_DETAILS_FAILED'
})
