export default Object.freeze({
  allUsers: '/all/users',
  superAdmin: '/super-admin',
  superAdminUser: '/super-admin/user/:id',
  superAdminOrg: '/super-admin/organization/:id',
  admin: '/admin/:id',
  application: '/application/:id/:initials',
  organisation: '/account',
  organisationPage: '/organization/:id',
  createOrganisation: '/organisation/create',
  formBuilder: '/form-builder/:jobId/:pipelineId/:pipelineTitle',
  home: '/',
  login: '/login',
  pageRegister: '/page-register',
  forgotPassword: '/page-forgot-password',
  verify: '/verify',
  test: '/test/:id',
  interview: '/interview',
  medicals: '/medicals',
  offer: '/offer',
  termsAndConditions: '/terms-and-conditions',
  institution: '/institution',
  profile: '/profile',
  editProfile:'/edit-profile',
  job: '/job/:id',
  jobs: '/job',
  apply: '/apply/:id',
  jobOffer: '/job-offer',
  kpi: '/kpi',
  allQuestion: '/all-questions',
  myApplications: '/my-applications',
  resetPassword: '/reset-password',
  message: '/message',
  talents: '/talents/:id',
  viewUser: '/view-user/:userId',
  pipelineManager: '/pipelines',
  pipeline: '/pipeline/:organization_id/:id',
  getPipeline: '/get-pipline/:id',
  createPipeline: '/create-pipeline/:section',
  medicalDashboard: '/medical-dashboard/:organization_id/:jobId/:id',
  medicalSettings: '/medical-settings/:organization_id/:jobId/:id',
  applicationDashboard:'/applicationform-dashboard/:organization_id/:jobId/:id',
  applicationSettings: '/application-settings/:organization_id/:jobId/:id',
  interviewDashboard: '/interview-dashboard/:organization_id/:jobId/:id',
  interviewSettings: '/interview-settings/:organization_id/:jobId/:id',
  cbtDashboard: '/exam-dashboard/:organization_id/:jobId/:id',
  cbtSettings: '/exam-settings/:organization_id/:jobId/:id',
  officialLetter:"/officialletter-dashboard/:organization_id/:jobId/:id",
  officialSettings:"/official-settings/:pipelineId",
  notifications:"/notifications",

  // fake routes... please replcae with the correct routes when made available
  examinations: "/examinations",
  applicationForm: "/applicationForm",
  medicals: "/medicals",
  interviewApplicant: "/interviewApplicant",
})
